### ISSUE TITLE
Fix issues with passwords over 8 characters long

### ISSUE THREAD

**Issue by markunca** [robertklep/bosch-xmpp#14]
Hi,
when running `env DEBUG=* bosch-xmpp --serial=XXX --access-key=XXX --password=XXX easycontrol get /` on RPi4, I am getting loop:

xmpp:client:session start socket connection +0ms
  xmpp:connection setup socket +0ms
  xmpp:connection use lazy socket +4ms
  xmpp:connection setup stream +2ms
  xmpp:connection send: <stream:stream xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" version="1.0" to="charlie.ticx.boschtt.net"> +79ms
  xmpp:connection receive: <?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" from="charlie.ticx.boschtt.net" id="9yy12gcuxr" xml:lang="en" version="1.0"> +23ms
  xmpp:connection receive: <stream:features><starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"><required/></starttls><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>SCRAM-SHA-1</mechanism><mechanism>DIGEST-MD5</mechanism></mechanisms></stream:features> +20ms
  xmpp:connection send: <starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"/> +2ms
  xmpp:connection receive: <proceed xmlns="urn:ietf:params:xml:ns:xmpp-tls"/> +23ms
  xmpp:connection use standard socket +31ms

I guess I will need to force different xmpp client, any idea?
Thank you

**Comment by robertklep** [comment]
I don't see a loop. But your issue may be related to your RPi's OpenSSL configuration: https://github.com/robertklep/nefit-easy-http-server#problems-on-recent-linux-distributions

**Comment by markunca** [comment]
Thank you, changing minimal required SSL move me one step forward but unfortunately still not fully operational. Here is the log:

xmpp:client:session start socket connection +0ms
  xmpp:connection setup socket +0ms
  xmpp:connection use lazy socket +8ms
  xmpp:connection setup stream +2ms
  xmpp:connection send: <stream:stream xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" version="1.0" to="charlie.ticx.boschtt.net"> +92ms
  xmpp:connection receive: <?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" from="charlie.ticx.boschtt.net" id="agt8nleow6" xml:lang="en" version="1.0"> +29ms
  xmpp:connection receive: <stream:features><starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"><required/></starttls><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>SCRAM-SHA-1</mechanism><mechanism>DIGEST-MD5</mechanism></mechanisms></stream:features> +23ms
  xmpp:connection send: <starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"/> +5ms
  xmpp:connection receive: <proceed xmlns="urn:ietf:params:xml:ns:xmpp-tls"/> +27ms
  xmpp:connection use standard socket +70ms
  xmpp:connection setup stream +1ms
  xmpp:connection send: <stream:stream xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" version="1.0" to="charlie.ticx.boschtt.net"> +93ms
  xmpp:connection receive: <?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" from="charlie.ticx.boschtt.net" id="agt8nleow6" xml:lang="en" version="1.0"><stream:features><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>SCRAM-SHA-1</mechanism><mechanism>DIGEST-MD5</mechanism></mechanisms><compression xmlns="http://jabber.org/features/compress"><method>zlib</method></compression><ver xmlns="urn:xmpp:features:rosterver"/></stream:features> +27ms
  xmpp:connection send: <auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="SCRAM-SHA-1">biwsbj1ycmMyY29udGFjdF8xMDEwNzQwODUscj1jY2Y2NWJmZjZmNTgyOWY5MmQ1ZjYxYzE4NDNlNDI3Nw==</auth> +22ms
  xmpp:connection receive: <challenge xmlns="urn:ietf:params:xml:ns:xmpp-sasl">cj1jY2Y2NWJmZjZmNTgyOWY5MmQ1ZjYxYzE4NDNlNDI3NzRmODNiMDdlLTQ0YzItNDc3Zi04MTRiLTMwOTFlZDYwZTEwZixzPXpRdE9JVnhyVVlHTHppeDJrQVhEekFLR0gveGppZzBJLGk9NDA5Ng==</challenge> +29ms
  xmpp:connection send: <response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">Yz1iaXdzLHI9Y2NmNjViZmY2ZjU4MjlmOTJkNWY2MWMxODQzZTQyNzc0ZjgzYjA3ZS00NGMyLTQ3N2YtODE0Yi0zMDkxZWQ2MGUxMGYscD1uZitiY0JrbEd4cEZ6OHBtVDVheDZva0cxNzQ9</response> +2s
  xmpp:connection receive: <success xmlns="urn:ietf:params:xml:ns:xmpp-sasl">dj1XazlkU1QvRW5yOFpGWElFR08veHRxSHl1WU09</success> +39ms
  xmpp:connection send: <stream:stream xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" version="1.0" to="charlie.ticx.boschtt.net"> +2ms
  xmpp:connection receive: <?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" from="charlie.ticx.boschtt.net" id="agt8nleow6" xml:lang="en" version="1.0"><stream:features><compression xmlns="http://jabber.org/features/compress"><method>zlib</method></compression><ver xmlns="urn:xmpp:features:rosterver"/><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"/><session xmlns="urn:ietf:params:xml:ns:xmpp-session"><optional/></session></stream:features> +26ms
  xmpp:connection send: <bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"/> +4ms
  xmpp:connection receive: <iq type="result" id="bind" to="charlie.ticx.boschtt.net/agt8nleow6"><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"><jid>rrc2contact_101074085@charlie.ticx.boschtt.net/agt8nleow6</jid></bind></iq> +32ms
  xmpp:connection send: <session xmlns="urn:ietf:params:xml:ns:xmpp-session"/> +4ms
  xmpp:connection receive: <iq type="result" id="sess" from="charlie.ticx.boschtt.net" to="rrc2contact_101074085@charlie.ticx.boschtt.net/agt8nleow6"/> +27ms
  bosch-easyremote online, jid = rrc2contact_101074085@charlie.ticx.boschtt.net/agt8nleow6 +0ms
  xmpp:connection send: <presence/> +7ms
  bosch-easyremote preparing message: / (retries = 0) +19ms
  bosch-easyremote queuing request (retries = 0) +2ms
  bosch-easyremote sending message +3ms
  bosch-easyremote:raw <message to="rrc2gateway_101074085@charlie.ticx.boschtt.net" type="chat"><body>GET / HTTP/1.1
  bosch-easyremote:raw User-Agent: rrc2
  bosch-easyremote:raw Seq-No: 1
  bosch-easyremote:raw 
  bosch-easyremote:raw 
  bosch-easyremote:raw </body></message> +0ms
  xmpp:connection send: <message to="rrc2gateway_101074085@charlie.ticx.boschtt.net" type="chat"><body>GET / HTTP/1.1
  xmpp:connection User-Agent: rrc2
  xmpp:connection Seq-No: 1
  xmpp:connection 
  xmpp:connection 
  xmpp:connection </body></message> +21ms
  xmpp:connection receive: <message to="rrc2contact_101074085@charlie.ticx.boschtt.net/agt8nleow6" type="chat" xml:lang="en" from="rrc2gateway_101074085@charlie.ticx.boschtt.net/RRC-RestApi"><body>HTTP/1.1 200 OK
  xmpp:connection Seq-No: 1
  xmpp:connection Content-Length: 364
  xmpp:connection Content-Type: application/json
  xmpp:connection Connection: close
  xmpp:connection 
  xmpp:connection /3OM0v+rUtMW4qz5ks3wItiI72FvSDyO3+X0+vXbR7EkJ0SMUaYOV1BB+fV9Y7hHkxEbzyJ3INL0RRQ6erQffCgziH/qAYQjGeIwz0/fK+XjKPT2PxJaMmz4EsPGnfHFS20+hyEJq8S/r2EzH7rG0gYthC+ik0OdizGM9MIbqGl0KMQRTzTqB6mEL/Fa+Omo1ZIcTH2QAMWLWh+RFwOvgTa1YiU9xG6gjtNLCrdwn8z+x5CEUlAGkrZvCdlriigkwD9NE0SCyHaOn+FftRD6+EB6BysNnseFFE1SRmlM71INvJBCF9xIsblBZpdkVL65LlIcgxhslYYaj+00FYRm9peOX+XYe5GmuVtAF/YMh4Y=</body></message> +187ms
  bosch-easyremote received stanza of type "message" +191ms
  bosch-easyremote:raw <message to="rrc2contact_101074085@charlie.ticx.boschtt.net/agt8nleow6" type="chat" xml:lang="en" from="rrc2gateway_101074085@charlie.ticx.boschtt.net/RRC-RestApi" xmlns:stream="http://etherx.jabber.org/streams"><body>HTTP/1.1 200 OK
  bosch-easyremote:raw Seq-No: 1
  bosch-easyremote:raw Content-Length: 364
  bosch-easyremote:raw Content-Type: application/json
  bosch-easyremote:raw Connection: close
  bosch-easyremote:raw 
  bosch-easyremote:raw /3OM0v+rUtMW4qz5ks3wItiI72FvSDyO3+X0+vXbR7EkJ0SMUaYOV1BB+fV9Y7hHkxEbzyJ3INL0RRQ6erQffCgziH/qAYQjGeIwz0/fK+XjKPT2PxJaMmz4EsPGnfHFS20+hyEJq8S/r2EzH7rG0gYthC+ik0OdizGM9MIbqGl0KMQRTzTqB6mEL/Fa+Omo1ZIcTH2QAMWLWh+RFwOvgTa1YiU9xG6gjtNLCrdwn8z+x5CEUlAGkrZvCdlriigkwD9NE0SCyHaOn+FftRD6+EB6BysNnseFFE1SRmlM71INvJBCF9xIsblBZpdkVL65LlIcgxhslYYaj+00FYRm9peOX+XYe5GmuVtAF/YMh4Y=</body></message> +190ms
  bosch-easyremote cleaning up for / +7ms
SyntaxError: Unexpected token � in JSON at position 0
    at JSON.parse (<anonymous>)
    at /usr/lib/node_modules/bosch-xmpp/lib/base-client.js:224:30
    at tryCatcher (/usr/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/usr/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:461:21)

**Comment by robertklep** [comment]
Assuming that you're talking to a CT200 (and the client, `easycontrol`, is the correct one), this typically means the password isn't correct. Also, make sure you put single quotes around it on the command line:
```
bosch-xmpp --serial=XXX --access-key=XXX --password='XXX' easycontrol get /
```

If you have a long(-ish) password (say 8 characters or more) and you're _sure_ it's correct, let me know, because that's an issue that I've had with the Nefit client as well.

**Comment by markunca** [comment]
Yes, I am having CT200 and EasyControl app

Tried it again, clarify password with login on web and it is correct. Password is longer then 8 characters.

**Comment by robertklep** [comment]
Okay, in that case I'll have to find out how the EasyControl app handles longer passwords, but that may take a while.

If you want a quick solution, you need to change your password to at most 8 characters for now.

**Comment by markunca** [comment]
Thank for info.
I will need to wait as I tried to change password and minimum lenght of password is 10 characters


![Screenshot 2021-04-19 at 14 11 47](https://user-images.githubusercontent.com/6464432/115234448-5529f700-a119-11eb-9f31-3a5880090b21.png)

**Comment by robertklep** [comment]
Change it in the EasyControl app, that allows for shorter passwords.

**Comment by markunca** [comment]
With shorter password it is working without any problem, thanks for tip.

**Comment by HHasenack** [comment]
Sorry for crossposting on the closed issue. I run into the same problems. 
** UPDATE**
Nevermind, I had mis-read the serial number. Now works like a charm!

Regards - Hans

**Comment by robertklep** [comment]
@markunca I changed the password to 12 characters and it still works for me 🤔

**Comment by axello** [comment]
FYI: My password is also 12 characters and it works fine. Temporarily running bosch-xmpp on macOS 11.6.
