### ISSUE TITLE
Unmanaged statusCode: 403 statusMasssage: Forbidden

### ISSUE THREAD

**Issue by isty1974** [robertklep/bosch-xmpp#2]
pi@raspberrypi:~ $ **bosch-xmpp ivt get /gateway**
_{"id":"/gateway","type":"refEnum","references":[{"id":"/gateway/uuid","uri":"http://192.168.0.201/gateway/uuid"},{"id":"/gateway/firmware","uri":"http://192.168.0.201/gateway/firmware"},{"id":"/gateway/userpassword","uri":"http://192.168.0.201/gateway/userpassword"},{"id":"/gateway/versionFirmware","uri":"http://192.168.0.201/gateway/versionFirmware"},{"id":"/gateway/versionHardware","uri":"http://192.168.0.201/gateway/versionHardware"},{"id":"/gateway/boschSHPassword","uri":"http://192.168.0.201/gateway/boschSHPassword"},{"id":"/gateway/portalPassword","uri":"http://192.168.0.201/gateway/portalPassword"},{"id":"/gateway/knxPassword","uri":"http://192.168.0.201/gateway/knxPassword"},{"id":"/gateway/haiPassword","uri":"http://192.168.0.201/gateway/haiPassword"},{"id":"/gateway/openIPPassword","uri":"http://192.168.0.201/gateway/openIPPassword"},{"id":"/gateway/openIPAccess","uri":"http://192.168.0.201/gateway/openIPAccess"},{"id":"/gateway/DateTime","uri":"http://192.168.0.201/gateway/DateTime"},{"id":"/gateway/instPassword","uri":"http://192.168.0.201/gateway/instPassword"},{"id":"/gateway/instAccess","uri":"http://192.168.0.201/gateway/instAccess"},{"id":"/gateway/instWriteAccess","uri":"http://192.168.0.201/gateway/instWriteAccess"},{"id":"/gateway/version","uri":"http://192.168.0.201/gateway/version"},{"id":"/gateway/update","uri":"http://192.168.0.201/gateway/update"},{"id":"/gateway/logging","uri":"http://192.168.0.201/gateway/logging"}]}_

just for fun...

pi@raspberrypi:~ $ **bosch-xmpp ivt get /gateway/knxPassword**
_{ Error: INVALID_RESPONSE
    at pending.(anonymous function).send.then.response (/usr/local/lib/node_modules/bosch-xmpp/lib/base-client.js:206:25)
    at tryCatcher (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
  response:
   { protocolVersion: 'HTTP/1.0',
     statusCode: '403',
     statusMessage: 'Forbidden',
     headers: {},
     body: '\r\n' } }_

Please handle this type of error message.

**Comment by robertklep** [comment]
How do you suggest to handle it? Perhaps use `statusMessage` as the error message?
