### ISSUE TITLE
CT200 with 03.06.03 requests software version on connection init

### ISSUE THREAD

**Issue by pszafer** [robertklep/bosch-xmpp#22]
Hi,
I'm author of HA custom component of Bosch and since version 03.06.03 of CT200/TC100v2 many users have problem with stable connection.
Your app is not working for them as well.
I found out that during initialization of connection XMPP server is querying client for software version https://xmpp.org/extensions/xep-0092.html

Unfortunately I can't find out what server expects to be returned. If wrong software version is returned then it requests disconnect from all clients (MyMode app is disconnecting as well according to reports).
Do you have any way to find out what it expects to return.
I tried several guesses without any luck
```python
async def handler(iq):
            print("software version request from {!r}".format(iq.from_))
            result = Query()
            result.name = "com.bosch.tt.buderus.controlng"
            result.version = "3.6.0"
            result.os = "Android 10"
            return result

self.xmppclient.stream.register_iq_request_handler(
    aioxmpp.IQType.GET,
    Query,
    handler,
)
```

**Comment by robertklep** [comment]
@pszafer at what point does the connection get terminated? I do see the version requests coming in:
```
  xmpp:connection receive: <iq type="get" id="259-25211931" to="XXX@xmpp.rrcng.ticx.boschtt.net/YYY" from="xmpp.rrcng.ticx.boschtt.net"><query xmlns="jabber:iq:version"/></iq> +5s
```
But my code ignores those, and the connection seems to be maintained (at least during a quick 5-minute check).

**Comment by robertklep** [comment]
@pszafer also, have you seen #20? The server name for the CT200 XMPP server has changed.

**Comment by pszafer** [comment]
Hi, yes. I'm using new server.
Connection is terminated after first message send from me `/gateway/uuid`.
Normally I'd say that user uses wrong password, but they (2 people) say that their password is correct, so I'm digging and this iq request is only thing I can find which might be the problem...
```
Error: MAX_RETRIES_REACHED             
    at HOME/.npm-global/lib/node_modules/bosch-xmpp/lib/base-client.js:181:51
    at tryCatcher (HOME/.npm-global/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (HOME/.npm-global/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (HOME/.npm-global/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (HOME/.npm-global/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (HOME/.npm-global/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (HOME/.npm-global/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (HOME/.npm-global/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (HOME/.npm-global/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (HOME/.npm-global/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:464:21)                                                                  
Error: MAX_RETRIES_REACHED                          
    at HOME/.npm-global/lib/node_modules/bosch-xmpp/lib/base-client.js:181:51
    at tryCatcher (HOME/.npm-global/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (HOME/.npm-global/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (HOME/.npm-global/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (HOME/.npm-global/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (HOME/.npm-global/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (HOME/.npm-global/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (HOME/.npm-global/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (HOME/.npm-global/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (HOME/.npm-global/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:15:14)
```

**Comment by robertklep** [comment]
Seems to be working fine for me:
```
$ ./bin/bosch-xmpp easycontrol get /gateway/uuid
{"id":"/gateway/uuid","type":"stringValue","writeable":0,"recordable":0,"value":"XXX"}
```

Also a longer-running connection using the built-in HTTP-to-XMPP bridge keeps working for me 🤔

`MAX_RETRIES_REACHED` typically points to the Bosch device not having an internet connection (it gets thrown if the code hasn't gotten a response for a request within 2 seconds, for 15 consecutive times).

**Comment by Kinyuu** [comment]
@pszafer Do you by any chance have issues with the CT200 connection in >=3.6.3?

**Comment by pszafer** [comment]
I got reply from user (I don't have this device), he changed WiFi channel and it started working. Old channel was 11. Now it is 6 I think.

**Comment by pszafer** [comment]
@Kinyuu little off topic do you know something about `/energy/history`? Like why for many users it is not working or stopped working and what is the meaning of each key.

**Comment by Kinyuu** [comment]
@pszafer What do you mean with stopped working? Does it return an HTTP error code?

**Comment by pszafer** [comment]
no, entries are returned, but max entry is placed in April or May and after that most return 0 (they use just hot water in summer time) eg:
Last value:
```
{               
            "T": 17.0,
            "d": "07-04-2021",
            "eCH": 6.97,
            "eHW": 7.06,
            "eSH": 0.0,
            "elec": 0.0,                                                                                                                                                                                                                       
            "wSH": 0.0
        }
```

After that:
```
{
            "T": 19.9,
            "d": "05-10-2021",
            "eCH": 0.0,
            "eHW": 0.0,
            "eSH": 0.0,
            "elec": 0.0,
            "wSH": 0.0
        }
```

**Comment by Kinyuu** [comment]
And how many entries are there in that /history and how many are reported in /energy/historyEntries ?

**Comment by pszafer** [comment]
```
{
    "available": "true",
    "id": "/energy/historyEntries",
    "maxValue": 6400.0,
    "minValue": 0.0,
    "recordable": 0,
    "stepSize": 1.0,
    "type": "floatValue",
    "unitOfMeasure": "",
    "used": "true",
    "value": 202.0,
    "writeable": 0
}
```

max entry is 201 today:
```
2021-10-07 13:10:50 INFO (MainThread) [bosch_thermostat_client.bosch_cli] Query succeed: /energy/history?entry=201
{
    "available": "true",
    "id": "/energy/history",
    "recordable": 0,
    "type": "energyRecordings",
    "used": "true",
    "value": [
        {
            "T": 19.4,
            "d": "06-10-2021",
            "eCH": 0.0,
            "eHW": 0.0,
            "eSH": 0.0,
            "elec": 0.0,
            "wSH": 0.0
        }
    ],
    "writeable": 0
}
```
As far as we know:
```
d: date
eCH: Energy Usage Central Heating
eHW: Energy Usage Hot Water
T: Average Temperature
```

**Comment by robertklep** [comment]
From a decompiled Android app:
```
        realmSet$energyUsageCentralHeating(f);
        realmSet$energyUsageHotWater(f2);
        realmSet$energyUsageSmartShower(f3);
        realmSet$waterUsageSmartShower(f4);
        realmSet$electricityUsage(f5);
        realmSet$averageTemperature(f6);
```

So `SH` is related to something called a "smart shower".

**Comment by Kinyuu** [comment]
@pszafer Robert already posted the other entries for history. 
As to why you stopped having entries other than '0', are you sure that your appliance as no issue and that in fact it is actually burning normally? The CT200 should only show values reported by the appliance.

**Comment by pszafer** [comment]
@Kinyuu, I saw Robert reply, thanks!
I've just found out that they have solar panels, so appliance returns 0 and it is correct.

@Kinyuu or maybe @robertklep  do you have any knowledge about how KM200 is generating kWh in `/heatSources/energyMonitoring/consumption` or what is unit in `/recordings/heatSources/actualPower`?

If you have, maybe you can join this issue https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/issues/88 and help out getting m3 value.

**Comment by robertklep** [comment]
@pszafer when I was working on the Nefit Easy code, the conversion factor [was hardcoded](https://github.com/robertklep/nefit-easy-core/wiki/List-of-endpoints#overall-gas-usage-ytd). I don't know how the EasyControl app handles this, but I assume it's something similar (since it cannot know the calorific value of your local gas supply). Since I don't actually run a CT200 I can't compare its values with the actual values supplied by my meter.
