### ISSUE TITLE
Json exception when attempting to connect to Buderus TC100.2

### ISSUE THREAD

**Issue by jfhautenauven** [robertklep/bosch-xmpp#28]
Hi Robert,

Thanks for the library, i think it is valuable work.

I've been fiddling a bit with it in order to try to connect to a Buderus TC100.2 thermostat (easycontrol), equivalent of Bosch CT200.
I don't seem to be able to make it speak to me correctly.

Getting this error when sending this command to the bridge http://xxxxxxxx:3000/bridge/system/brand

```
TypeError [ERR_INVALID_CHAR]: Invalid character in statusMessage
    at ServerResponse.writeHead (_http_server.js:287:11)
    at ServerResponse.writeHead (/usr/local/lib/node_modules/bosch-xmpp/node_modules/on-headers/index.js:44:26)
    at ServerResponse._implicitHeader (_http_server.js:239:8)
    at write_ (_http_outgoing.js:654:9)
    at ServerResponse.end (_http_outgoing.js:766:5)
    at ServerResponse.send (/usr/local/lib/node_modules/bosch-xmpp/node_modules/express/lib/response.js:221:10)
    at /usr/local/lib/node_modules/bosch-xmpp/lib/cli/server.js:34:18
    at Layer.handle_error (/usr/local/lib/node_modules/bosch-xmpp/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/usr/local/lib/node_modules/bosch-xmpp/node_modules/express/lib/router/index.js:321:13)
    at /usr/local/lib/node_modules/bosch-xmpp/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/local/lib/node_modules/bosch-xmpp/node_modules/express/lib/router/index.js:341:12)
    at Immediate.next (/usr/local/lib/node_modules/bosch-xmpp/node_modules/express/lib/router/index.js:275:10)
    at Immediate._onImmediate (/usr/local/lib/node_modules/bosch-xmpp/node_modules/express/lib/router/index.js:641:15)
    at processImmediate (internal/timers.js:463:21)
```
    
In fact, I get this for all commands.
Another result i get with this command : http://xxxxxx:3000/bridge/gateway/DateTime

```
SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at /usr/local/lib/node_modules/bosch-xmpp/lib/base-client.js:224:30
    at tryCatcher (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:461:21)
  morgan log request +22s
```

Any clue ? 

I suspected password issue, so I have tested a short password with 10 char (minimum allowed by bosch) and one special character.
When I type the correct password, I tend to get more of the first error I showed above.
I definetely get ALWAYS the second type of error when the password is wrong.

I KNOW when I test (with good password) that my password is the right one. 

That's the only clue I got, I think it could be "encryption related".

HELP ! SOS! :)

**Comment by robertklep** [comment]
The JSON error is almost certainly related to the password: it means the library couldn't decrypt the payload to valid JSON (and then still tries to parse it and errors out).

What happens if you retrieve the endpoint `/system/brand` directly (without the bridge)?
```
$ bosch-xmpp … easycontrol get /system/brand
```

**Comment by jfhautenauven** [comment]
I get this response.

```
SyntaxError: Unexpected token in JSON at position 0
    at JSON.parse (<anonymous>)
    at /usr/local/lib/node_modules/bosch-xmpp/lib/base-client.js:224:30
    at tryCatcher (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:461:21)
```


The password I give to the command line is correct
It's something like 'Tests-1234'

I can log into the Bosch website with it and i use the same password to log into the "Buderus Mymode" application.

**Comment by robertklep** [comment]
It could be that Bosch has changed their password policy so passwords have to include special characters and be at least 10 characters long, because my passwords are shorter and don't have special characters in them.

I still have no idea how Bosch clients deal with longer passwords, because I've never gotten my client to work with those. Perhaps they get hashed and the client takes the first 8/10 characters of the hash, no idea. But it you can't change your password to at most 8 characters and without special characters in them, I don't know how to solve your problem.

**Comment by jfhautenauven** [comment]
Mmmh, I feared that it may be the problem indeed.

Do you have decompiled source of the Bosch app, to investigate if there exists some code there that may lead us to a clue ?

**Comment by robertklep** [comment]
Please send me an e-mail (robert AT klep DOT name)

**Comment by jfhautenauven** [comment]
@robertklep : for your information, passwords above 8 characters are sent to the XMPP backend using BASE64 encoding. Shorter passwords are not encoded. Hope it helps.

KR,
JFH

**Comment by robertklep** [comment]
Have you confirmed this to work? If so, it should be easy enough to implement 👍🏻

**Comment by jfhautenauven** [comment]
Will do some more testing, works fine here for my EasyControl system here.

**Comment by robertklep** [comment]
If you modified my client, feel free to create a PR so I can import your changes. Otherwise I'll implement it myself 😊

**Comment by jfhautenauven** [comment]
i didn't modify your client, i'm just passing the base64 encoded password to your command line :)

**Comment by robertklep** [comment]
Haha lol, nice solution 😂

I updated the client, can you check and see if it handled your password correctly now?

You can install it from Github directly:
```
npm install -g https://github.com/robertklep/bosch-xmpp
```

If it works, I'll publish a new version to the NPM repository.

**Comment by jfhautenauven** [comment]
I'll test on sunday and report to you. No problemo

**Comment by robertklep** [comment]
Thanks!

**Comment by jfhautenauven** [comment]
Hi Robert, tested on my side here, I give your lib the non encoded password, and I still manage to connect.
I guess the mystery is solved ? :D 

Would be good to have someone else to also test that stuff.

KR,
JFH

**Comment by robertklep** [comment]
The change I made should not cause issues with people having shorter passwords, so I'm fine with releasing it.

I also pushed a fix for your other issue, if you want to test it?

**Comment by jfhautenauven** [comment]
Hi Robert, I commented on the other issue, ... close but not cigar on that one.
Password one keeps on working. So I would propose, we close this issue (Json exception), and reopen the other one (gas history etc.)

Thanks in advance,

KR,

**Comment by robertklep** [comment]
@jfhautenauven following up on this issue.

I had to revert back the Base64-encoding of the password because of #32.

I dusted off my CT-200 (I don't use it so it was packed up in a box somewhere) and it seems that the client works just fine with passwords that are longer than 10 characters. For example, I tested with `Foobar-1234!` and it works just fine.

Can you confirm that your password is working with the current version of the package (v1.4.1) as well?

**Comment by jfhautenauven** [comment]
@robertklep Hi Robert, sorry for the long delay period, I had put this project in the cold storage due to lack of time.
Retested. Using a password longer than 8 chars, I get JSON Token errors or statusMessage bad errors.
Setting it to exactly 8 chars works. So I don't understand why it works on your side, and not on mine :/

**Comment by robertklep** [comment]
@jfhautenauven it may depend on firmware version, mine is now at 04.02.01, which was the latest firmware version when I updated it a week or two ago.

At that time I was e-mailing with a user that also had password issues, but it turned out that they were using their Bosch account password, not the device password. When we realised this their issues were solved, and they were able to use a longer password too.

**Comment by jfhautenauven** [comment]
What do you mean by device password ? 

Also running v04.02.01

**Comment by robertklep** [comment]
To use the official Bosch EasyControl app (on iOS/Android) you first have to register at Bosch with e-mail address and password to get a "BoschID". However, the password for that account is not the same as the password you set for the device, which can be set separately from the app.

**Comment by jfhautenauven** [comment]
I use the bosch ID, but I didn't know there was another password kind. Do you have extra info about that ? I could give it a shot

**Comment by robertklep** [comment]
In the EasyControl app, hamburger menu (top left), "Settings > Personal > Change Password". I think that changes the device password (not sure though).

**Comment by jfhautenauven** [comment]
Naaah, that was in the old days, now it brings you to the bosch ID logon page :/

**Comment by robertklep** [comment]
It doesn't for me (iOS):

![ADDEA727-CA84-4504-8229-16F4E8F58271_1_102_o](https://github.com/robertklep/bosch-xmpp/assets/1190916/eea1ef83-b32f-4e1a-bb06-e2be77bc2617)

When I change the password there, the device password is changed (confirmed with the `bosch-xmpp` CLI tool)

**Comment by jfhautenauven** [comment]
and so that is the password from the Password field that goes in there, right ?

**Comment by robertklep** [comment]
That's the password you can use with `bosch-xmpp`.

**Comment by jfhautenauven** [comment]
OK confirmed, this works ... woooaaah, how could Bosch come up with something that cryptic ?! 

Thanks for the info Robert, this is GOLD :)

**Comment by jfhautenauven** [comment]
I'll close the issue now, I understand what I had done wrong, and has nothing to do with your library :) Thanks again :)

**Comment by robertklep** [comment]
Glad to have been of help! 😊
