### ISSUE TITLE
setting values for IVT pump problem

### ISSUE THREAD

**Issue by GitDuff** [robertklep/bosch-xmpp#3]
Hi Robert,

I've been using the get functionality for my ivt pump for a longtime and was trying to use the "put" functionality to control the thermostat level but can't seem to manage it.

GET goes fine (obviously I've changed the parameters in the command line)

_bosch-xmpp --serial=12345678 --access-key=random5stuff --password=MyPa55w0rd ivt get /heatingCircuits/hc1/temperatureLevels/normal_
{"id":"/heatingCircuits/hc1/temperatureLevels/normal","type":"floatValue","writeable":1,"recordable":0,"value":20.5,"unitOfMeasure":"C","minValue":10,"maxValue":35}

I figured I'd try and set the Thermostat temperature level:
_bosch-xmpp --serial=12345678 --access-key=random5stuff --password=MyPa55w0rd ivt put /heatingCircuits/hc1/temperatureLevels/normal '{"value":19.5}'_
**Error: MAX_RETRIES_REACHED**
    at queueMessage.catch.e (/usr/local/lib/node_modules/bosch-xmpp/lib/base-client.js:179:51)
    at tryCatcher (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

Any tips or pointers where I might be going wrong would be grate help.

Thanks
Alan

**Comment by robertklep** [comment]
Do you have the latest version (1.0.2) installed? There was an issue with older versions that caused the `PUT` command to fail (although it didn't fail with that particular error).

Also, you could try and raise the default timeout, which is set to 2 seconds which might not be enough:
```
bosch-xmpp --timeout=60 --serial=12345678 --access-key=random5stuff ...
```

**Comment by GitDuff** [comment]
Bingo... was still running 1.0.1!
Sorry for the time wasting... should have checked that first :)

**Comment by robertklep** [comment]
No problem, glad it was an easy solve 😂
