### ISSUE TITLE
CT200 fails with password >8 characters

### ISSUE THREAD

**Issue by andrewbarnes666** [robertklep/bosch-xmpp#32]
I have 2 different installs, one using v1.3.0 the other using v1.4.0

With a password >8 characters, the installation with v1.4.0 fails with the following stack dump when trying to `get /zones/list` (for example)

`SyntaxError: Unexpected token � in JSON at position 0 at JSON.parse (<anonymous>) at /usr/local/lib/node_modules/bosch-xmpp/lib/base-client.js:224:30 at tryCatcher (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/util.js:16:23) at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:547:31) at Promise._settlePromise (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:604:18) at Promise._settlePromise0 (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:649:10) at Promise._settlePromises (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:729:18) at _drainQueueStep (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:93:12) at _drainQueue (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:86:9) at Async._drainQueues (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:102:5) at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:15:14) at processImmediate (node:internal/timers:464:21)`

v1.3.0 continues to work with >8 char for password

Now that I've reduced my password length to 8 char, v1.4.0 now works again successfully

**Node.js Version:** `16.13.0`
**NPM Version:** `8.4.0` (and `8.3.2`)
**Operating System:** `FreeBSD 12.2-RELEASE-p12` - running as an socage jail

**Comment by andrewbarnes666** [comment]
x-ref to the homebridge ct200 project where I found this issue [here](https://github.com/lynxcs/homebridge-ct200/issues/27)

**Comment by robertklep** [comment]
Ouch, that's annoying :( I'll revert the password "fix" and push 1.4.1 ASAP. I guess we need to do a bit more testing.

**Comment by andrewbarnes666** [comment]
NP, and thank you for the quick response (not to mention the awesome code!)
If you need any more environment details, please let me know (I'm running v3.10 firmware btw)
