### ISSUE TITLE
Getting syntax error from example

### ISSUE THREAD

**Issue by christian-ek** [robertklep/bosch-xmpp#37]
Hello!
I'm trying to run this example

```
const { IVTClient } = require('./bosch-xmpp');

// Instantiate client
const client = IVTClient({
  serialNumber: "removed",
  accessKey: "removed",
  password: "removed",
});

client.connect().then(() => {
  return client.get('/gateway/versionFirmware');
}).then(response => {
  console.log('%j', response);
}).catch(e => {
  console.error(e.stack || e);
}).finally(() => {
  client.end();
});
```

but getting this:
```
SyntaxError: Unexpected token # in JSON at position 0
    at JSON.parse (<anonymous>)
    at /Volumes/development/bosch-xmpp/lib/base-client.js:224:30
    at tryCatcher (/Volumes/development/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Volumes/development/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Volumes/development/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Volumes/development/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Volumes/development/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/Volumes/development/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Volumes/development/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Volumes/development/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Volumes/development/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:466:21)
```

Via commandline is working thou:
```
bosch-xmpp --verbose ivt get /gateway/versionFirmware --serial=removed --access-key='removed' --password='removed'                                                                           19:02:54
{"id":"/gateway/versionFirmware","type":"stringValue","writeable":0,"recordable":0,"value":"04.08.02"}
```

**Comment by christian-ek** [comment]
Sorry bout this. Turns out I wrote the wrong password. Now it's working

**Comment by robertklep** [comment]
@christian-ek no problem 😊
