### ISSUE TITLE
How to put a value to the Easycontrol CT200

### ISSUE THREAD

**Issue by VanDeStouwe** [robertklep/bosch-xmpp#41]
I'm able to get quitte a bit of information using get's. As for example would like to change from clock mode to manual mode. Using get gives the response:
`cmd>bosch-xmpp --serial=xxxxx --access-key=xxxxx --password=xxxx easycontrol get /zones/zn1/userMode
{"id":"/zones/zn1/userMode","type":"stringValue","writeable":1,"used":"true","recordable":0,"value":"clock"}`
and when in manual i get:
`{"id":"/zones/zn1/userMode","type":"stringValue","writeable":1,"used":"true","recordable":0,"value":"manual"}`

If I follow other put examples i have to use the following commandline to change to manual but something is wrong:
`cmd>bosch-xmpp --serial=xxx --access-key=xxxx --password=xxx easycontrol put /zones/zn1/userMode '{"value":"manual"}'
Unhandled rejection SyntaxError: Unexpected token ' in JSON at position 0
    at JSON.parse (<anonymous>)
    at C:\Users\Sidney van de Stouwe\AppData\Roaming\npm\node_modules\bosch-xmpp\lib\cli\index.js:63:51
    at tryCatcher (C:\Users\Sidney van de Stouwe\AppData\Roaming\npm\node_modules\bosch-xmpp\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Sidney van de Stouwe\AppData\Roaming\npm\node_modules\bosch-xmpp\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\Sidney van de Stouwe\AppData\Roaming\npm\node_modules\bosch-xmpp\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\Sidney van de Stouwe\AppData\Roaming\npm\node_modules\bosch-xmpp\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\Sidney van de Stouwe\AppData\Roaming\npm\node_modules\bosch-xmpp\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Users\Sidney van de Stouwe\AppData\Roaming\npm\node_modules\bosch-xmpp\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\Sidney van de Stouwe\AppData\Roaming\npm\node_modules\bosch-xmpp\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\Sidney van de Stouwe\AppData\Roaming\npm\node_modules\bosch-xmpp\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\Users\Sidney van de Stouwe\AppData\Roaming\npm\node_modules\bosch-xmpp\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:471:21)`

What is wrong with the put data?

**Comment by robertklep** [comment]
It might be a Windows thing, not sure (and can't test since I don't use Windows).

If you set the environment variable `DEBUG` to contain the value `*` (I don't know how to do that in Windows either) it should show you more information, hopefully providing a clue why it's not working.

**Comment by VanDeStouwe** [comment]
When I installed npm i got the following warnings:
```
C:\Users\Sidney van de Stouwe>npm install -g bosch-xmpp
npm WARN deprecated node-xmpp-tls-connect@1.0.1: this package is deprecated please use https://github.com/xmppjs/xmpp.jsnpm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated node-xmpp-core@5.0.9: this package is deprecated please use https://github.com/xmppjs/xmpp.js
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-xmpp-client@3.2.0: this package is deprecated please use https://www.npmjs.com/package/@xmpp/client
```

Can ignore this?

I activated the DEBUG * resulting in:
```
  xmpp:client:session start socket connection +0ms
  xmpp:connection setup socket +0ms
  xmpp:connection use lazy socket +1ms
  xmpp:connection setup stream +0ms
  xmpp:connection send: <stream:stream xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" version="1.0" to="xmpp.rrcng.ticx.boschtt.net"> +51ms
  xmpp:connection receive: <?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" from="xmpp.rrcng.ticx.boschtt.net" id="5goq4ei32i" xml:lang="en" version="1.0"> +26ms
  xmpp:connection receive: <stream:features><starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"><required/></starttls><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>SCRAM-SHA-1</mechanism></mechanisms></stream:features> +74ms  xmpp:connection send: <starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"/> +3ms
  xmpp:connection receive: <proceed xmlns="urn:ietf:params:xml:ns:xmpp-tls"/> +23ms
  xmpp:connection use standard socket +61ms
  xmpp:connection setup stream +0ms
  xmpp:connection send: <stream:stream xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" version="1.0" to="xmpp.rrcng.ticx.boschtt.net"> +131ms
  xmpp:connection receive: <?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" from="xmpp.rrcng.ticx.boschtt.net" id="5goq4ei32i" xml:lang="en" version="1.0"><stream:features><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>SCRAM-SHA-1</mechanism></mechanisms><compression xmlns="http://jabber.org/features/compress"><method>zlib</method></compression><ver xmlns="urn:xmpp:features:rosterver"/><c xmlns="http://jabber.org/protocol/caps" hash="sha-1" node="https://www.igniterealtime.org/projects/openfire/" ver="WBW9aq73MmnFx8LEeAVdzlvdefs="/></stream:features> +28ms
  xmpp:connection send: <auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="SCRAM-SHA-1">biwsbj1ycmMyY29udGFjdF8xMDE0ODMyODIscj1kZThiMzQ1Mzg0OWMxZWRmMzY5M2Y4YTc1NzZhN2U1ZQ==</auth> +9ms
  xmpp:connection receive: <challenge xmlns="urn:ietf:params:xml:ns:xmpp-sasl">cj1kZThiMzQ1Mzg0OWMxZWRmMzY5M2Y4YTc1NzZhN2U1ZWRlMWIzODg1LTViNzktNGRkZi1iMDNkLWU1ZTdmNDcyMzJiNSxzPXlBeUZneHlkNERpdjYweEROZlpNR1V5QmFYOXdzZFhzLGk9NDA5Ng==</challenge> +37ms
  xmpp:connection send: <response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">Yz1iaXdzLHI9ZGU4YjM0NTM4NDljMWVkZjM2OTNmOGE3NTc2YTdlNWVkZTFiMzg4NS01Yjc5LTRkZGYtYjAzZC1lNWU3ZjQ3MjMyYjUscD1HYnFYOTVpVS95YWVVSHJDNWd6Q2xBNkhTQms9</response> +181ms
  xmpp:connection receive: <success xmlns="urn:ietf:params:xml:ns:xmpp-sasl">dj00Q3BydzBjRHJJbklVNlhRR1ZhVWZSdWRRdGM9</success> +23ms
  xmpp:connection send: <stream:stream xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" version="1.0" to="xmpp.rrcng.ticx.boschtt.net"> +0ms
  xmpp:connection receive: <?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" from="xmpp.rrcng.ticx.boschtt.net" id="5goq4ei32i" xml:lang="en" version="1.0"><stream:features><compression xmlns="http://jabber.org/features/compress"><method>zlib</method></compression><ver xmlns="urn:xmpp:features:rosterver"/><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"/><session xmlns="urn:ietf:params:xml:ns:xmpp-session"><optional/></session><c xmlns="http://jabber.org/protocol/caps" hash="sha-1" node="https://www.igniterealtime.org/projects/openfire/" ver="WBW9aq73MmnFx8LEeAVdzlvdefs="/></stream:features> +22ms
  xmpp:connection send: <bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"/> +0ms
  xmpp:connection receive: <iq type="result" id="bind" to="xmpp.rrcng.ticx.boschtt.net/5goq4ei32i"><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"><jid>rrc2contact_101483282@xmpp.rrcng.ticx.boschtt.net/5goq4ei32i</jid></bind></iq> +27ms
  xmpp:connection send: <session xmlns="urn:ietf:params:xml:ns:xmpp-session"/> +0ms
  xmpp:connection receive: <iq type="result" id="sess" from="xmpp.rrcng.ticx.boschtt.net" to="rrc2contact_101483282@xmpp.rrcng.ticx.boschtt.net/5goq4ei32i"/> +24ms
  bosch-easyremote online, jid = rrc2contact_101483282@xmpp.rrcng.ticx.boschtt.net/5goq4ei32i +0ms
  xmpp:connection send: <presence/> +2ms
Unhandled rejection SyntaxError: Unexpected token ' in JSON at position 0
    at JSON.parse (<anonymous>)
    at C:\Users\Sidney van de Stouwe\AppData\Roaming\npm\node_modules\bosch-xmpp\lib\cli\index.js:63:51
    at tryCatcher (C:\Users\Sidney van de Stouwe\AppData\Roaming\npm\node_modules\bosch-xmpp\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Sidney van de Stouwe\AppData\Roaming\npm\node_modules\bosch-xmpp\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\Sidney van de Stouwe\AppData\Roaming\npm\node_modules\bosch-xmpp\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\Sidney van de Stouwe\AppData\Roaming\npm\node_modules\bosch-xmpp\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\Sidney van de Stouwe\AppData\Roaming\npm\node_modules\bosch-xmpp\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Users\Sidney van de Stouwe\AppData\Roaming\npm\node_modules\bosch-xmpp\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\Sidney van de Stouwe\AppData\Roaming\npm\node_modules\bosch-xmpp\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\Sidney van de Stouwe\AppData\Roaming\npm\node_modules\bosch-xmpp\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\Users\Sidney van de Stouwe\AppData\Roaming\npm\node_modules\bosch-xmpp\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:471:21)
```

**Comment by robertklep** [comment]
It looks like the Windows shell might be passing the single quotes around your JSON as-is (as opposed to on Unix).

Try running the command without them: 
```
bosch-xmpp --serial=xxx --access-key=xxxx --password=xxx easycontrol put /zones/zn1/userMode {"value":"manual"}
```

And yes, you can ignore those warnings 😊

**Comment by VanDeStouwe** [comment]
Ok I tried on my Raspberry IV and there it works like a charm. So it is definitly a windows thing I will do some node.js debugging to see what is going wrong

**Comment by robertklep** [comment]
It's very likely the Windows shell that's causing this and not so much Node.js 😁

**Comment by VanDeStouwe** [comment]
**The input line is percent encoded like %7B%22 for { and "**
**I added a statement to see how it was translated. That learned that I lost the {} and the "" signs. The follwing works fine**:
`C:\Users\Sidney van de Stouwe>bosch-xmpp --serial=x --access-key=x --password=x easycontrol put /zones/zn1/userMode {\"value\":\"manual\"}
output added statement: JSON data: {"value":"manual"}

{"status":"ok"}`
