### ISSUE TITLE
bosch-xmpp  ivt put /heatingCircuits/hc1/operationMode '{"value":"manual"}' fails with 404

### ISSUE THREAD

**Issue by rachedamer** [robertklep/bosch-xmpp#48]
Getting JSON values seems to work fine, but as soon as I try to put something, after a long time I get 

$ bosch-xmpp  ivt put /heatingCircuits/hc1/operationMode '{"value":"manual"}' 
Error: INVALID_RESPONSE
    at /usr/lib/node_modules/bosch-xmpp/lib/base-client.js:257:23
    at tryCatcher (/usr/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/usr/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21) {
  response: {
    protocolVersion: 'HTTP/1.0',
    statusCode: '404',
    statusMessage: 'Not Found',
    headers: {},
    body: ''
  }
}

**Comment by robertklep** [comment]
This is the same as #47.

I don't have an IVT device myself so I have no idea why these requests are failing. For the Nefit Easy and the EasyControl they work, perhaps IVT works differently.
